version: '3'

services:
  transportpce:
    image: odl/transportpce
    volumes: 
      - ./conf/remoteodl.properties:/opt/opendaylight/etc/remoteodl.properties
    environment: 
      - REMOTE_SDNRURL=http://sdnr:8181
      - REMOTE_WSURL=ws://sdnr:8181/websocket
      - REMOTE_ODL_USERNAME=${SDNR_USERNAME}
      - REMOTE_ODL_PASSWORD=${SDNR_PASSWORD}
      - REMOTE_ODL_ENABLED=${REMOTE_ODL_ENABLED}
      - REMOTE_ODL_TRUSTALL=${TRUSTALL}
    depends_on: 
      - sdnr
  sdncweb:
   #    image: nexus3.onap.org:10001/onap/sdnc-web-image:latest
    image: 10.20.6.10:30000/hightec/sdnc-web-image:2.0.0-SNAPSHOT-20200731T064656Z
    environment: 
      - SDNRHOST=sdnr
    depends_on: 
      - sdnr
  sdnr:
    image: nexus3.onap.org:10001/onap/sdnc-image:2.2.5
    environment: 
      - ODL_ADMIN_PASSWORD=${SDNR_PASSWORD}
      - SDNRONLY=true
      - SDNRINIT=true
      - SDNRDM=true
      - SDNRWT=true
      - SDNRDBURL=http://sdnrdb:9200
      - SDNRWT_BOOTFEATURES=odl-netconf-callhome-ssh,sdnr-wt-feature-aggregator
#    entrypoint: /opt/onap/sdnc/bin/startODL.oom.sh
    depends_on: 
      - sdnrdb
  sdnrdb:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.4
    environment: 
      - discovery.type=single-node
  roadma:
    image: ${HONEYNODE_IMAGE}
    environment: 
      - USER=${HONEYNODE_REST_USER} 
      - PASSWORD=${HONEYNODE_REST_PASSWORD}
      - DEVICE_VERSION=${HONEYNODE_VERSION}
      - DEVICE_FILE=${HONEYNODE_VERSION}/oper-ROADMA.xml
    depends_on: 
      - sdnr
  roadmb:
    image: ${HONEYNODE_IMAGE}
    environment: 
      - USER=${HONEYNODE_REST_USER} 
      - PASSWORD=${HONEYNODE_REST_PASSWORD}
      - DEVICE_VERSION=${HONEYNODE_VERSION}
      - DEVICE_FILE=${HONEYNODE_VERSION}/oper-ROADMB.xml
    depends_on: 
      - sdnr
  roadmc:
    image: ${HONEYNODE_IMAGE}
    environment: 
      - USER=${HONEYNODE_REST_USER} 
      - PASSWORD=${HONEYNODE_REST_PASSWORD}
      - DEVICE_VERSION=${HONEYNODE_VERSION}
      - DEVICE_FILE=${HONEYNODE_VERSION}/oper-ROADMC.xml
    depends_on: 
      - sdnr  
  xpdra:
    image: ${HONEYNODE_IMAGE}
    environment: 
      - USER=${HONEYNODE_REST_USER} 
      - PASSWORD=${HONEYNODE_REST_PASSWORD}
      - DEVICE_VERSION=${HONEYNODE_VERSION}
      - DEVICE_FILE=${HONEYNODE_VERSION}/oper-XPDRA.xml
    depends_on: 
      - sdnr      
  xpdrc:
    image: ${HONEYNODE_IMAGE}
    environment: 
      - USER=${HONEYNODE_REST_USER} 
      - PASSWORD=${HONEYNODE_REST_PASSWORD}
      - DEVICE_VERSION=${HONEYNODE_VERSION}
      - DEVICE_FILE=${HONEYNODE_VERSION}/oper-XPDRC.xml
    depends_on: 
      - sdnr
                                          
