version: '3'
services:
  transportpce:
    container_name: transportpce
    image: odl/transportpce
    environment: 
      - REMOTE_SDNRURL=${REMOTE_SDNR_URL}
      - REMOTE_WSURL=${REMOTE_SDNR_WSURL}
      - REMOTE_ODL_USERNAME=${SDNR_USERNAME}
      - REMOTE_ODL_PASSWORD=${SDNR_PASSWORD}
      - REMOTE_ODL_ENABLED=${REMOTE_ODL_ENABLED}
      - REMOTE_ODL_TRUSTALL=${TRUSTALL}
      - TRANSPORTPCE_SIMULATOR_MODE=false
    ports: 
      - '18181:8181'
    volumes:
      - ./conf/org.opendaylight.transportpce.cfg:/opt/opendaylight/etc/org.opendaylight.transportpce.cfg

  roadma:
    image: ${NTSIM_ROADM_STANDALONE_IMAGE}
    container_name: roadma
    environment: 
      - NTS_IP=10.20.11.121
      - EXTERNAL_NTS_IP=10.20.11.121
      - NETCONF_BASE=${SIMPORT}
      - SCRIPTS_DIR=/opt/dev/scripts
      - K8S_DEPLOYMENT=false
      - IPv6Enabled=false
    volumes: 
      - ./conf/ntsim_configuration.json:/opt/dev/scripts/configuration.json
      - ./conf/oper-ROADMA.xml:/opt/dev/scripts/startup-load.xml
    ports: 
      - 50010:${SIMPORT}

  roadmb:
    image: ${NTSIM_ROADM_STANDALONE_IMAGE}
    container_name: roadmb
    environment: 
      - NTS_IP=10.20.11.121
      - EXTERNAL_NTS_IP=10.20.11.121
      - NETCONF_BASE=${SIMPORT}
      - SCRIPTS_DIR=/opt/dev/scripts
      - K8S_DEPLOYMENT=false
      - IPv6Enabled=false
    volumes: 
      - ./conf/ntsim_configuration.json:/opt/dev/scripts/configuration.json
      - ./conf/oper-ROADMB.xml:/opt/dev/scripts/startup-load.xml
    ports: 
      - 50011:${SIMPORT}

  roadmc:
    image: ${NTSIM_ROADM_STANDALONE_IMAGE}
    container_name: roadmc
    environment: 
      - NTS_IP=10.20.11.121
      - EXTERNAL_NTS_IP=10.20.11.121
      - NETCONF_BASE=${SIMPORT}
      - SCRIPTS_DIR=/opt/dev/scripts
      - K8S_DEPLOYMENT=false
      - IPv6Enabled=false
    volumes: 
      - ./conf/ntsim_configuration.json:/opt/dev/scripts/configuration.json
      - ./conf/oper-ROADMC.xml:/opt/dev/scripts/startup-load.xml
    ports: 
      - 50012:${SIMPORT}

  xpdra:
    image: ${NTSIM_ROADM_STANDALONE_IMAGE}
    container_name: xpdra
    environment: 
      - NTS_IP=10.20.11.121
      - EXTERNAL_NTS_IP=10.20.11.121
      - NETCONF_BASE=${SIMPORT}
      - SCRIPTS_DIR=/opt/dev/scripts
      - K8S_DEPLOYMENT=false
      - IPv6Enabled=false
    volumes: 
      - ./conf/ntsim_configuration.json:/opt/dev/scripts/configuration.json
      - ./conf/oper-XPDRA.xml:/opt/dev/scripts/startup-load.xml  
    ports: 
      - 50013:${SIMPORT}

  xpdrc:
    image: ${NTSIM_ROADM_STANDALONE_IMAGE}
    container_name: xpdrc
    environment: 
      - NTS_IP=10.20.11.121
      - EXTERNAL_NTS_IP=10.20.11.121
      - NETCONF_BASE=${SIMPORT}
      - SCRIPTS_DIR=/opt/dev/scripts
      - K8S_DEPLOYMENT=false
      - IPv6Enabled=false
    volumes: 
      - ./conf/ntsim_configuration.json:/opt/dev/scripts/configuration.json
      - ./conf/oper-XPDRC.xml:/opt/dev/scripts/startup-load.xml                                          
    ports: 
      - 50014:${SIMPORT}
