version: '3'
services:
  transportpce:
    container_name: transportpce
    image: odl/transportpce
    environment: 
      - REMOTE_SDNRURL=${REMOTE_SDNR_URL}
      - REMOTE_WSURL=${REMOTE_SDNR_WSURL}
      - REMOTE_ODL_USERNAME=${SDNR_USERNAME}
      - REMOTE_ODL_PASSWORD=${SDNR_PASSWORD}
      - REMOTE_ODL_ENABLED=${REMOTE_ODL_ENABLED}
      - REMOTE_ODL_TRUSTALL=${TRUSTALL}
      - TRANSPORTPCE_SIMULATOR_MODE=false
    ports: 
      - '18181:8181'
    volumes:
      - ./conf/org.opendaylight.transportpce.cfg:/opt/opendaylight/etc/org.opendaylight.transportpce.cfg

  roadma:
    image: ${NTSNG_IMAGE}
    container_name: roadma
    environment: 
      - NTS_NF_STANDALONE_START_FEATURES="datastore-populate"
      - NTS_NF_MOUNT_POINT_ADDRESSING_METHOD=host-mapping # mapping types: host-mapping, docker-mapping
      - NTS_HOST_IP=${NTS_HOST_IP}
      - HOSTNAME=roadma
      - IPv6_ENABLED=false
      - SSH_CONNECTIONS=1
      - TLS_CONNECTIONS=0
      - NTS_HOST_NETCONF_SSH_BASE_PORT=${SIMPORT}
      - NTS_HOST_NETCONF_TLS_BASE_PORT=65500
    volumes: 
      - ./conf/ntsng.config.json:/opt/dev/ntsim-ng/config/config.json
      - ./conf/oper-ROADMA-operational.xml:/opt/dev/deploy/data/org-openroadm-device-operational.xml
      # - ./conf/oper-ROADMA-pm-operational.xml:/opt/dev/deploy/data/org-openroadm-pm-operational.xml
      # - ./conf/oper-ROADMA-syslog-operational.xml:/opt/dev/deploy/data/org-openroadm-syslog-operational.xml
      - ./conf/oper-ROADMA-running.xml:/opt/dev/deploy/data/org-openroadm-device-running.xml
      # - ./conf/oper-ROADMA-pm-running.xml:/opt/dev/deploy/data/org-openroadm-pm-running.xml
      # - ./conf/oper-ROADMA-syslog-running.xml:/opt/dev/deploy/data/org-openroadm-syslog-running.xml
    ports: 
      - 50010:${SIMPORT}

  roadmb:
    image: ${NTSNG_IMAGE}
    container_name: roadmb
    environment: 
      - NTS_NF_STANDALONE_START_FEATURES="datastore-populate"
      - NTS_NF_MOUNT_POINT_ADDRESSING_METHOD=host-mapping # mapping types: host-mapping, docker-mapping
      - NTS_HOST_IP=${NTS_HOST_IP}
      - HOSTNAME=roadma
      - IPv6_ENABLED=false
      - SSH_CONNECTIONS=1
      - TLS_CONNECTIONS=0
      - NTS_HOST_NETCONF_SSH_BASE_PORT=${SIMPORT}
      - NTS_HOST_NETCONF_TLS_BASE_PORT=65500
    volumes: 
      - ./conf/ntsng.config.json:/opt/dev/ntsim-ng/config/config.json
      - ./conf/oper-ROADMB-operational.xml:/opt/dev/deploy/data/org-openroadm-device-operational.xml
      # - ./conf/oper-ROADMB-pm-operational.xml:/opt/dev/deploy/data/org-openroadm-pm-operational.xml
      # - ./conf/oper-ROADMB-syslog-operational.xml:/opt/dev/deploy/data/org-openroadm-syslog-operational.xml
      - ./conf/oper-ROADMB-running.xml:/opt/dev/deploy/data/org-openroadm-device-running.xml
      # - ./conf/oper-ROADMB-pm-running.xml:/opt/dev/deploy/data/org-openroadm-pm-running.xml
      # - ./conf/oper-ROADMB-syslog-running.xml:/opt/dev/deploy/data/org-openroadm-syslog-running.xml
    ports: 
      - 50011:${SIMPORT}

  roadmc:
    image: ${NTSNG_IMAGE}
    container_name: roadmc
    environment: 
      - NTS_NF_STANDALONE_START_FEATURES="datastore-populate"
      - NTS_NF_MOUNT_POINT_ADDRESSING_METHOD=host-mapping # mapping types: host-mapping, docker-mapping
      - NTS_HOST_IP=${NTS_HOST_IP}
      - HOSTNAME=roadma
      - IPv6_ENABLED=false
      - SSH_CONNECTIONS=1
      - TLS_CONNECTIONS=0
      - NTS_HOST_NETCONF_SSH_BASE_PORT=${SIMPORT}
      - NTS_HOST_NETCONF_TLS_BASE_PORT=65500
    volumes: 
      - ./conf/ntsng.config.json:/opt/dev/ntsim-ng/config/config.json
      - ./conf/oper-ROADMC-operational.xml:/opt/dev/deploy/data/org-openroadm-device-operational.xml
      # - ./conf/oper-ROADMC-pm-operational.xml:/opt/dev/deploy/data/org-openroadm-pm-operational.xml
      # - ./conf/oper-ROADMC-syslog-operational.xml:/opt/dev/deploy/data/org-openroadm-syslog-operational.xml
      - ./conf/oper-ROADMC-running.xml:/opt/dev/deploy/data/org-openroadm-device-running.xml
      # - ./conf/oper-ROADMC-pm-running.xml:/opt/dev/deploy/data/org-openroadm-pm-running.xml
      # - ./conf/oper-ROADMC-syslog-running.xml:/opt/dev/deploy/data/org-openroadm-syslog-running.xml
    ports: 
      - 50012:${SIMPORT}

  xpdra:
    image: ${NTSNG_IMAGE}
    container_name: xpdra
    environment: 
      - NTS_NF_STANDALONE_START_FEATURES="datastore-populate"
      - NTS_NF_MOUNT_POINT_ADDRESSING_METHOD=host-mapping # mapping types: host-mapping, docker-mapping
      - NTS_HOST_IP=${NTS_HOST_IP}
      - HOSTNAME=roadma
      - IPv6_ENABLED=false
      - SSH_CONNECTIONS=1
      - TLS_CONNECTIONS=0
      - NTS_HOST_NETCONF_SSH_BASE_PORT=${SIMPORT}
      - NTS_HOST_NETCONF_TLS_BASE_PORT=65500
    volumes: 
      - ./conf/ntsng.config.json:/opt/dev/ntsim-ng/config/config.json
      - ./conf/oper-XPDRA-operational.xml:/opt/dev/deploy/data/org-openroadm-device-operational.xml
      # - ./conf/oper-XPDRA-pm-operational.xml:/opt/dev/deploy/data/org-openroadm-pm-operational.xml
      # - ./conf/oper-XPDRA-syslog-operational.xml:/opt/dev/deploy/data/org-openroadm-syslog-operational.xml
      - ./conf/oper-XPDRA-running.xml:/opt/dev/deploy/data/org-openroadm-device-running.xml
      # - ./conf/oper-XPDRA-pm-running.xml:/opt/dev/deploy/data/org-openroadm-pm-running.xml
      # - ./conf/oper-XPDRA-syslog-running.xml:/opt/dev/deploy/data/org-openroadm-syslog-running.xml
    ports: 
      - 50013:${SIMPORT}

  xpdrc:
    image: ${NTSNG_IMAGE}
    container_name: xpdrc
    environment: 
      - NTS_NF_STANDALONE_START_FEATURES="datastore-populate"
      - NTS_NF_MOUNT_POINT_ADDRESSING_METHOD=host-mapping # mapping types: host-mapping, docker-mapping
      - NTS_HOST_IP=${NTS_HOST_IP}
      - HOSTNAME=roadma
      - IPv6_ENABLED=false
      - SSH_CONNECTIONS=1
      - TLS_CONNECTIONS=0
      - NTS_HOST_NETCONF_SSH_BASE_PORT=${SIMPORT}
      - NTS_HOST_NETCONF_TLS_BASE_PORT=65500
    volumes: 
      - ./conf/ntsng.config.json:/opt/dev/ntsim-ng/config/config.json
      - ./conf/oper-XPDRC-operational.xml:/opt/dev/deploy/data/org-openroadm-device-operational.xml
      # - ./conf/oper-XPDRC-pm-operational.xml:/opt/dev/deploy/data/org-openroadm-pm-operational.xml
      # - ./conf/oper-XPDRC-syslog-operational.xml:/opt/dev/deploy/data/org-openroadm-syslog-operational.xml
      - ./conf/oper-XPDRC-running.xml:/opt/dev/deploy/data/org-openroadm-device-running.xml
      # - ./conf/oper-XPDRC-pm-running.xml:/opt/dev/deploy/data/org-openroadm-pm-running.xml
      # - ./conf/oper-XPDRC-syslog-running.xml:/opt/dev/deploy/data/org-openroadm-syslog-running.xml                           
    ports: 
      - 50014:${SIMPORT}
