[simulation]
perf-sim-10 ansible_host=10.20.35.236 ansible_connection=ssh ansible_user=ubuntu
perf-sim-11 ansible_host=10.20.35.168 ansible_connection=ssh ansible_user=ubuntu
perf-sim-12 ansible_host=10.20.35.235 ansible_connection=ssh ansible_user=ubuntu
perf-sim-13 ansible_host=10.20.35.237 ansible_connection=ssh ansible_user=ubuntu
perf-sim-14 ansible_host=10.20.35.217 ansible_connection=ssh ansible_user=ubuntu
perf-sim-15 ansible_host=10.20.35.210 ansible_connection=ssh ansible_user=ubuntu
perf-sim-16 ansible_host=10.20.35.233 ansible_connection=ssh ansible_user=ubuntu