<?xml version="1.0" encoding="UTF-8"?>
<!--
 * ============LICENSE_START=======================================================
 * ONAP : CCSDK.feature.sdnr.wt
 * ================================================================================
 * Copyright (C) 2018 highstreet technologies GmbH Intellectual Property.
 * All rights reserved.
 * ================================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============LICENSE_END=========================================================
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.opendaylight.odlparent</groupId>
    <artifactId>odlparent-lite</artifactId>
    <version>7.0.8</version>
    <relativePath />
  </parent>

  <groupId>org.opendaylight.transportpce</groupId>
  <artifactId>transportpce-installer</artifactId>
  <version>4.2.0</version>
  <packaging>pom</packaging>

  <name>ccsdk-features :: ${project.artifactId}</name>

  <properties>
    <application.name>sdnc-transportpce-feature-aggregator</application.name>
    <include.transitive.dependencies>true</include.transitive.dependencies>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.opendaylight.transportpce</groupId>
      <artifactId>odl-transportpce</artifactId>
      <version>${project.version}</version>
      <type>xml</type>
      <classifier>features</classifier>
    </dependency>
    <dependency>
      <groupId>org.opendaylight.transportpce</groupId>
      <artifactId>odl-transportpce-dmaap-client</artifactId>
      <version>${project.version}</version>
      <type>xml</type>
      <classifier>features</classifier>
    </dependency>
    <dependency>
      <groupId>org.opendaylight.transportpce</groupId>
      <artifactId>odl-transportpce-tapi</artifactId>
      <version>${project.version}</version>
      <type>xml</type>
      <classifier>features</classifier>
    </dependency>
    <dependency>
      <groupId>org.opendaylight.transportpce</groupId>
      <artifactId>odl-transportpce-inventory</artifactId>
      <version>${project.version}</version>
      <type>xml</type>
      <classifier>features</classifier>
    </dependency>
    <dependency>
      <groupId>org.opendaylight.transportpce</groupId>
      <artifactId>odl-transportpce-nbinotifications</artifactId>
      <version>${project.version}</version>
      <type>xml</type>
      <classifier>features</classifier>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-assembly-plugin</artifactId>
        <executions>
          <execution>
            <id>maven-repo-zip</id>
            <goals>
              <goal>single</goal>
            </goals>
            <phase>package</phase>
            <configuration>
              <attach>true</attach>
              <finalName>stage/${application.name}-${project.version}</finalName>
              <descriptors>
                <descriptor>src/assembly/assemble_mvnrepo_zip.xml</descriptor>
              </descriptors>
              <appendAssemblyId>true</appendAssemblyId>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>copy-nested-dependencies</id>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <phase>prepare-package</phase>
            <configuration>
              <transitive>false</transitive>
              <excludeTransitive>false</excludeTransitive>
              <!-- <includeGroupIds>org.opendaylight.transportpce,org.glassfish.jersey.ext,org.glassfish.jersey.media,com.fasterxml.jackson.datatype,org.jgrapht</includeGroupIds> -->
              <includeGroupIds>org.opendaylight.transportpce,org.opendaylight.transportpce.ordmodels,org.onap.ccsdk.features.sdnr.wt</includeGroupIds>
              <outputDirectory>${project.build.directory}/assembly/system</outputDirectory>
              <overWriteReleases>false</overWriteReleases>
              <overWriteSnapshots>true</overWriteSnapshots>
              <overWriteIfNewer>true</overWriteIfNewer>
              <useRepositoryLayout>true</useRepositoryLayout>
              <addParentPoms>false</addParentPoms>
              <copyPom>false</copyPom>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
  <reporting>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-project-info-reports-plugin</artifactId>
        <version>2.9</version>
      </plugin>
    </plugins>
  </reporting>
</project>